FROM python:3.11.0 as builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Установка необходимых пакетов
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    postgresql \
    gcc \
    python3-dev \
    musl-dev

# Установка pip и зависимостей
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Создание wheel пакетов для оптимальной установки
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

# Основной образ
FROM python:3.11.0

# Создание пользовательской группы и пользователя
RUN groupadd app && useradd -m -g app app

# Установка переменных окружения
ENV HOME=/home/app
ENV APP_HOME=/home/app/django

# Создание необходимых директорий
RUN mkdir -p $APP_HOME /home/app/django/media /home/app/django/static

WORKDIR $APP_HOME

# Установка netcat для проверки доступности базы данных
RUN apt-get update && apt-get install -y netcat

# Копирование wheel пакетов и установка зависимостей
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --no-cache /wheels/*

# Копирование кода приложения
COPY . $APP_HOME
COPY ./repet_django/static $APP_HOME/static1

# Настройка прав и доступов
RUN chown -R app:app $APP_HOME

# Копирование entrypoint и установка прав
COPY entrypoint.prod.sh $APP_HOME/entrypoint.prod.sh
# RUN chmod +x $APP_HOME/entrypoint.prod.sh

# Установка прав на директории
# RUN chown -R app:app /home/app/django/media /home/app/django/static
# RUN chown -R app:app /home/app/django
# RUN chmod -R 777 /home/app/django/media /home/app/django/static
RUN chmod -R 777 /home/app/django

# Переключение на пользователя `app`
# USER app


# Установка точки входа
ENTRYPOINT ["/home/app/django/entrypoint.prod.sh"]