version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/mike:/var/lib/postgresql/data
    env_file:
      - .env
  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: django
    depends_on:
      - postgres
    volumes:
      - static_volume:/mike/static
      - media_volume:/mike/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate  && gunicorn -b 127.0.0.1:8000 repet_django.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    image: nginx
    volumes:
      - static_volume:/mike/static
      - media_volume:/mike/media
    depends_on:
      - django_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
