version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
  django:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: "gunicorn repet_django.wsgi:application --bind 0.0.0.0:8000"
    container_name: django
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/mike/static
      - media_volume:/usr/src/mike/media
    env_file:
      - .env.prod
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: