version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      bash -c "./manage.py collectstatic --noinput &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    container_name: django
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - static_volume:/usr/src/mike/static
      - media_volume:/usr/src/mike/media
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume: